header:
  - license:
      copyright-owner: Canonical Ltd.
      copyright-year: 2025
      content: |
        Copyright [year] [owner]
        Licensed under the Apache2.0. See LICENSE file in charm source for details.
    paths:
      - 'lib/**'
    comment: on-failure
  - license:
      spdx-id: Apache-2.0
      copyright-owner: Canonical Ltd.
      content: |
        Copyright [year] [owner]
        See LICENSE file for licensing details.
    paths:
      - '**'
      - 'charms/worker/k8s/lib/charms/k8s/**'
    paths-ignore:
      - 'charms/worker/k8s/lib/charms/**'
      - 'tests/integration/data/*.tar.gz'
      - '.github/**'
      - '**/*.patch'
      - '**/.gitkeep'
      - '**/*.cfg'
      - '**/*.conf'
      - '**/*.ini'
      - '**/*.j2'
      - '**/*.json'
      - '**/*.md'
      - '**/*.rule'
      - '**/*.tmpl'
      - '**/*.txt'
      - '**/*.xml'
      - '**/*.lock'
      - '.codespellignore'
      - '.dockerignore'
      - '.flake8'
      - '.jujuignore'
      - '.gitignore'
      - '.licenserc.yaml'
      - '.trivyignore'
      - '.woke.yaml'
      - '.woke.yml'
      - 'CODEOWNERS'
      - 'icon.svg'
      - 'LICENSE'
      - '.charmcraft-channel'
      - 'pyproject.toml'
      - 'trivy.yaml'
      - 'zap_rules.tsv'
      - 'lib/**'
    comment: on-failure
