# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

amd64:
  - name: k8s
    install-type: store
    classic: true
    revision: 5501
arm64:
  - name: k8s
    install-type: store
    classic: true
    revision: 5500
