# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

amd64:
- install-type: store
  name: k8s
  # should be 5279. changed to the value below for testing
  revision: 5044
arm64:
- install-type: store
  name: k8s
  # should be 5280. changed to the value below for testing
  revision: 5047
