# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

# Code generated by "config_change_preventer"; DO NOT EDIT.

"""Bootstrap config change preventer."""

import logging
from typing import Optional, Union

from ops import ErrorStatus, Object
from protocols import K8sCharmProtocol

import charms.contextual_status as status

log = logging.getLogger(__name__)

_ConfigValueType = Union[str, int, float, bool]


class BootstrapConfigChangePreventer(Object):
    """Prevent bootstrap config changes after bootstrap."""

    def __init__(self, charm: K8sCharmProtocol, refresh_events: Optional[list]):
        """Initialize the BootstrapConfigChangePreventer object."""
        super().__init__(charm, "bootstrap-config-change-preventer")
        self._charm = charm
        self._refresh_events = refresh_events or [self._charm.on.config_changed]
        for evt in self._refresh_events:
            self.framework.observe(evt, self._prevent_config_change)

    def _prevent_config_change(self, event):
        """Prevent bootstrap config changes after bootstrap."""
        bootstrap_configs = self._get_bootstrap_configs()
        self._charm.stored_state.set_default(default_bootstrap_configs=bootstrap_configs)

        changed = []
        for config, new_value in bootstrap_configs.items():
            old_value = self._charm.stored_state.default_bootstrap_configs.get(config)
            if old_value is None:
                # NOTE(Hue): This should not happen cause we've just set it
                log.error("Bootstrap config %s not found in stored state", config)
                continue

            if old_value != new_value:
                log.error(
                    "%s should NOT be changed after bootstrap. Cluster was bootstrapped with %s",
                    config,
                    old_value,
                )
                changed.append(config)

        if changed:
            status.add(
                ErrorStatus(
                    f"{', '.join(changed)} should NOT be changed after bootstrap. "
                    "Check the logs for more info."
                )
            )

        # NOTE(Hue): We don't update the stored state here because we want to preserve the
        # original values that were set at bootstrap time.

    def _get_bootstrap_configs(self) -> dict[str, _ConfigValueType]:
        """Get bootstrap configs."""
        bootstrap_configs: dict[str, _ConfigValueType] = {}
        for config, value in self._charm.config.items():
            if config.startswith("bootstrap-"):
                bootstrap_configs[config] = value
        return bootstrap_configs
