# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
# This file configures Charmcraft.
# See https://juju.is/docs/sdk/charmcraft-config for guidance.

name: k8s-worker
title: Kubernetes Worker
summary: A machine charm for a K8s Worker
description: |
  A machine charm which operates a Kubernetes worker.

  This charm installs and operates a Kubernetes worker via the k8s snap. It exposes
  relations to co-operate with other kubernetes components

  This charm provides the following running components:
  * kube-proxy
  * kubelet
  * containerd
links:
  contact: https://launchpad.net/~containers
  documentation: https://discourse.charmhub.io
  issues:
  - https://github.com/canonical/k8s-operator/issues
  source:
    - https://github.com/canonical/k8s-operator

assumes:
  - juju >= 3.1

type: charm
bases:
  - build-on:
    - name: ubuntu
      channel: "20.04"
      architectures: [amd64]
    run-on:
    - name: ubuntu
      channel: "20.04"
      architectures: [amd64]
    - name: ubuntu
      channel: "22.04"
      architectures: [amd64]
config:
  options:
    channel:
      default: edge
      type: string
      description: |
        Snap channel to install k8s snap from

requires:
  cluster:
    # TODO: confirm this should be a new relation or maybe kube-control
    interface: k8s-cluster