name: Auto-update K8s charm libraries

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@347c04309d21e628f2114c24947931141ee921a3
    secrets: inherit
    with:
      working-directory:  ./charms/worker/k8s
