name: Auto-update K8s charm libraries

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@a935f80df0b6cf2821210300fe51940fc2858297
    secrets: inherit
    with:
      working-directory:  ./charms/worker/k8s
