name: Auto-update K8s charm libraries

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@721ef586b04340e2d3129f540923cc62b63fd1bf
    secrets: inherit
    with:
      working-directory:  ./charms/worker/k8s
