name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@b9b4fd8a3e37f9b3b450fb62f2a8f39385db4ef4
    secrets: inherit
