name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@55a2fb9668d5b6a15f5e9693fdfb1d6a62018fac
    secrets: inherit
