name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@49d016bc4928fe8fb704b2694e3dfc2b5906a52c
    secrets: inherit
