name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@8373ffba960898c9726b4bf60627e8575b2c0740
    secrets: inherit
