name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@bc4db021dab5fb8daf8590688f230c4a6e613f76
    secrets: inherit
