name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@0ffbcf4619d7c28ae66bbc33f206f4b6c7bc4d4f
    secrets: inherit
