name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@1bbe0ad7a454ce50e5d966bc60d733fcc2c3f9d3
    secrets: inherit
