name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@e48fe7835253893205e1697bd2abe9a94cef7d2f
    secrets: inherit
