name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@40215aadfbe0fc85a66224fcb9520482f3cb4785
    secrets: inherit
