name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@81409b668682e5b66e1a714e582d9aac850a32e8
    secrets: inherit
