name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@9355505dfc20a9518b345c24e6666e1ed12fbb66
    secrets: inherit
