name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@1e4b911fd9284ddd560ac7fab6d16de4c2afc023
    secrets: inherit
