name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@449328cc2b1b3314db26ad4793b20ea1058c14c1
    secrets: inherit
