name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@29eb49f6df457cb503a8aceb8e30df34d80d2d02
    secrets: inherit
