name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@a1954613d81c99550a6c837e2abb03c9bc3a94c7
    secrets: inherit
