name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@262226a2c1bb43105ea08b9a36bd97a2a57f45a3
    secrets: inherit
