name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@46c6c5833954cf14de96d1e2879801d01753617c
    secrets: inherit
