name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@3dab3973fc18d7622c4b2adc3ee362f51302f5b8
    secrets: inherit
