name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@56d52394219e4ba7b2f3b92883b0dbb66ce549f2
    secrets: inherit
