name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@696e7c698eec3d2d057bf775dd4e954f41ab022e
    secrets: inherit
