name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@c415a47cdc45a7c03f105863c03717939412480f # main
    secrets: inherit
