name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: addyess/operator-workflows/.github/workflows/bot_pr_approval.yaml@issue/683/pinnable-workflows
    secrets: inherit
