name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@0f30cac55cea1123568e3c9237fb1fcddd9d2442
    secrets: inherit
