name: Provide approval for bot PRs

on:
#  pull_request:
  workflow_dispatch:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@main
    secrets: inherit
