name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@1adf2138eaa5dfe42ac8ef5305f15c7a2c56ba14
    secrets: inherit
