name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@1c44a5862e9954a1e41682c1630b622278cae90e
    secrets: inherit
