name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/bot_pr_approval.yaml@f726594f3f6230ddb2e2df0e25fb8b28bdc6c083
    secrets: inherit
