name: Charm Analysis
# Unit testing, Style Linting, Type Linting, Static Analysis, and Spelling

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@7fd34e293481827c89f3876c274f6e7bd6c0d873
    secrets: inherit
    with:
      charm-directory: charms
      self-hosted-runner:  false
