name: Charm Analysis
# Unit testing, Style Linting, Type Linting, Static Analysis, and Spelling

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@347c04309d21e628f2114c24947931141ee921a3
    secrets: inherit
    with:
      charm-directory: charms
      self-hosted-runner:  false
