name: Charm Analysis
# Unit testing, Style Linting, Type Linting, Static Analysis, and Spelling

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@3646a29c06e87d1ac89665c532dc21ac9fbf4692
    secrets: inherit
    with:
      charm-directory: charms
      self-hosted-runner:  false
