name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Charm Analysis"]
    types:
      - completed

jobs:
  comment-on-pr:
    uses: addyess/operator-workflows/.github/workflows/comment.yaml@issue/683/pinnable-workflows
    secrets: inherit
