name: Comment on the pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'track/**'

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@72ba44455ad0ba7ec1c51027d5360357d1925733 # main
    secrets: inherit
