name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment.yaml@7fd34e293481827c89f3876c274f6e7bd6c0d873
    secrets: inherit
