name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Charm Analysis"]
    types:
      - completed

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment.yaml@5f7c5ae8edce88c84ce33ac9674995fa551e3e75 # main
    secrets: inherit
