name: Comment on the pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'track/**'

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@c639731f99b0926e5dcbfe2b93fe7261d6eeadfb
    secrets: inherit
