name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Charm Analysis"]
    types:
      - completed

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment.yaml@1e2cab8312dc6e0b8da15f78f098c61b50b5fd73 # main
    secrets: inherit
