name: Comment on the pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'track/**'

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@449328cc2b1b3314db26ad4793b20ea1058c14c1
    secrets: inherit
