name: Comment on the pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'track/**'

jobs:
  comment-on-pr:
    uses: addyess/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@issue/683/pinnable-workflows
    secrets: inherit
