name: Comment on the pull request

on:
  workflow_dispatch:
#  pull_request:
#    types:
#      - opened
#    branches:
#      - 'track/**'

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@main
    secrets: inherit
