name: Comment on the pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'track/**'

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@46c6c5833954cf14de96d1e2879801d01753617c
    secrets: inherit
