name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Charm Analysis"]
    types:
      - completed

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment.yaml@09cddf26ba3c7b66c09ad473063ac4fb6e2a55c9
    secrets: inherit
