name: Comment on the pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'track/**'

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@6438a2a4046d05e5ee349480dcb05aeb563f2456
    secrets: inherit
