name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Charm Analysis"]
    types:
      - completed

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment.yaml@1c44a5862e9954a1e41682c1630b622278cae90e
    secrets: inherit
