name: Load tests

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  load-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@347c04309d21e628f2114c24947931141ee921a3
    with:
      provider: lxd
      juju-channel: 3.3/stable
      load-test-enabled: true
      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
    secrets: inherit
