name: Load tests

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  charmcraft-channel:
    runs-on: ubuntu-24.04
    outputs:
      channel: ${{ steps.charmcraft.outputs.channel }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - id: charmcraft
      run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT

  load-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@d7de61956c117646a3b42ed4568468df5bb9b73e # main
    needs: [charmcraft-channel]
    secrets: inherit
    with:
      provider: lxd
      charmcraft-channel: ${{ needs.charmcraft-channel.outputs.channel }}
      juju-channel: 3/stable
