name: Load tests

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  load-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@3646a29c06e87d1ac89665c532dc21ac9fbf4692
    with:
      provider: lxd
      juju-channel: 3.3/stable
      load-test-enabled: true
      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
    secrets: inherit
