name: Promote charm

on:
  workflow_dispatch:
    inputs:
      charm:
        type: choice
        description: 'Charm'
        options:
        - k8s
        - k8s-worker
      origin-risk:
        type: choice
        description: 'Origin Channel'
        options:
        - edge
        - beta
        - candidate
      destination-risk:
        type: choice
        description: 'Destination Channel'
        options:
        - stable
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  configure-track:
    runs-on: ubuntu-latest
    outputs:
      track: ${{ steps.flags.outputs.track }}
    steps:
      - name: Determine Track
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          # look for a branch matching the re \^release-1.\d+$\
          if [[ "${BRANCH}" =~ "^release-1\.[0-9]+$" ]]; then
            echo "track=${BRANCH:8}" >> "$GITHUB_OUTPUT"
          else
            echo "track=latest" >> "$GITHUB_OUTPUT"
          fi
          echo "Promote from $track/${{github.event.inputs.origin-risk}} to $track/${{github.event.inputs.destination-risk}}"
  promote-charm:
    needs: [configure-track]
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{needs.configure-track.outputs.track}}/${{ github.event.inputs.origin-risk }}
      destination-channel: ${{needs.configure-track.outputs.track}}/${{ github.event.inputs.destination-risk }}
      docs-working-directory: ./charms
      working-directory:  ./charms/${{ github.event.inputs.charm == 'k8s-worker' && 'worker' || 'worker/k8s' }}
    secrets: inherit
