name: Publish K8s-worker to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: latest/edge
      working-directory:  ./charms/worker/k8s/
      tag-prefix: k8s-worker