name: TICS nightly quality scan

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: read

jobs:
  TICS:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Latest branches
          - { branch: main }

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout the Repository
        uses: actions/checkout@v4
        with:
          ref: ${{matrix.branch}}

      - name: Install Astral uv
        uses: astral-sh/setup-uv@v6

      - name: Install Dependencies
        run: |
          uv sync --project charms/worker/k8s
          source charms/worker/k8s/.venv/bin/activate
          uv pip install pylint flake8
          uv tool install tox --with tox-uv

      - name: Run Tests With Coverage
        run: |
          tox -e unit,coverage-xml
          # TiCS expects the report to be under a "$(pwd)/cover" directory.
          mkdir -p "$GITHUB_WORKSPACE/cover"
          GENERATED_COVERAGE_XML="$GITHUB_WORKSPACE/charms/worker/k8s/coverage.xml"
          mv "$GENERATED_COVERAGE_XML" cover/coverage.xml

      - name: Run TICS
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: ${{ github.event.repository.name }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
